export const homeData = [
  {
    id: 1,
    name: "Avengers: Endgame",
    rating: 4.7,
    time: "3hr : 1mins",
    desc: "After Thanos, an intergalactic warlord, disintegrates half of the universe, the Avengers must reunite and assemble again to reinvigorate their trounced allies and restore balance.",
    starring: "Robert Downey Jr., Chris EvansMark, Ruffalo",
    genres: "Action",
    tags: "Action, Adventures, Fantasy, Superheroes",
    cover: "../images/home1.jpg",
    video: "../video/video1.mp4",
    date: "24-Apr-2019",
  },
  {
    id: 2,
    name: "Joker (2019)",
    rating: 4.2,
    time: "2hr : 2mins",
    desc: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
    starring: "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
    genres: "Crime, Drama, Thriller",
    tags: "Crime, Dark, Thrilling, Unsettling",
    cover: "../images/home2.jpg",
    video: "../video/video2.mp4",
    date: "4-Oct-2019",
  },
  {
    id: 3,
    name: "Parasite",
    rating: 4.6,
    time: "2hr : 12mins",
    desc: "A poor family, the Kims, con their way into becoming the servants of a rich family, the Parks. But their easy life gets complicated when their deception is threatened with exposure.",
    starring: "Kang-ho Song, Sun-kyun Lee, Yeo-jeong Jo",
    genres: "Comedy, Drama, Thriller",
    tags: "Black Comedy, Social Commentary, Thrilling",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "30-May-2019",
  },
  {
    id: 4,
    name: "1917",
    rating: 4.3,
    time: "1hr : 59mins",
    desc: "During World War I, two British soldiers are given an impossible mission: deliver a message deep in enemy territory that will stop 1,600 men, and one of the soldier's brothers, from walking straight into a deadly trap.",
    starring: "Dean-Charles Chapman, George MacKay, Daniel Mays",
    genres: "Drama, War",
    tags: "Epic, Heartbreaking, Intense",
    cover: "../images/home4.jpg",
    video: "../video/video4.mp4",
    date: "4-Dec-2019",
  },
]
export const upcome = [
  {
    id: 1, 
    cover: "../images/upcome/u1.jpg", 
    name: "The Lion King", 
    time: "1hr : 58min",
  },
  {
    id: 2, 
    cover: "../images/upcome/u2.jpg",
     name: "Jumanji: The Next Level",
      time: "2hr : 3min",
  },
  {
    id: 3, 
    cover: "../images/upcome/u3.jpg", 
    name: "Fast & Furious Presents: Hobbs & Shaw", 
    time: "2hr : 17min",
  },
  {
    id: 4, 
    cover: "../images/upcome/u4.jpg", 
    name: "Frozen 2",
    time: "1hr : 43min",
  },
  {
    id: 5, 
    cover: "../images/upcome/u5.jpg",
    name: "Star Wars: The Rise of Skywalker", 
    time: "2hr : 22min"
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "King of Jungle",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "The illusion",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u1.jpg",
    name: "Latest Movie",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u5.jpg",
    name: "Latest two",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u4.jpg",
    name: "Latest Three",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "The Dinosaur",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/img/slide1.png",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "The Great Emperor",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Jumbo Queen",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2010",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
]
